SELECT 
in0.SOP3_LOAN_NO AS SOP3_LOAN_NO,
in0.SOP3_LNDR_NO AS SOP3_LNDR_NO,
in0.SOP3_REMIT_OPT AS SOP3_REMIT_OPT,
in0.SOP3_RCL_RPUR_DATE AS SOP3_RCL_RPUR_DATE,
in0.SOP3_GL_ENTITY_COD AS SOP3_GL_ENTITY_COD,
in0.SOP3_CONDUIT_CODE AS SOP3_CONDUIT_CODE,
in0.SOP3_ACC AS SOP3_ACC,
in0.SOP3_ACTL_UPB_ACQS AS SOP3_ACTL_UPB_ACQS,
in0.SOP3_LPI_ACQSN AS SOP3_LPI_ACQSN,
in0.SOP3_INT_PURD AS SOP3_INT_PURD,
in0.SOP3_PASS_THRU_RATE AS SOP3_PASS_THRU_RATE,
in0.SOP3_LOAN_TYPE AS SOP3_LOAN_TYPE
FROM {{ ref('QUALIFIER_SQ_RDW_RECLASS__DAT_0') }} AS in0 
JOIN ( SELECT MAX(UNIQUE_ID) AS UNIQUE_ID 
FROM {{ ref('QUALIFIER_SQ_RDW_RECLASS__DAT_0') }} AS in0 )
AS AGG_AUTOALIAS  ON AGG_AUTOALIAS.UNIQUE_ID = in0.UNIQUE_ID