SELECT seq2.nextval as UNIQUE_ID,
	Cast ( trim(documentdatametainfo_payloadgroup_payloadinfo_payloadfilemetainfo_recordcoun ) as DECIMAL(1,0)) as documentdatametainfo_payloadgroup_payloadinfo_payloadfilemetainfo_recordcoun 
	FROM RDW_reclass__meta_0